spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              url: https://dev-04812936.okta.com/app/dev-04812936_tryinsaml_1/exki3bf5031rzzRsD5d7/slo/saml
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: "classpath:metadata/metadata-idp-okta.xml"

logging:
  level:
    org:
      springframework:
        security: DEBUG
